# Generated by Django 5.2 on 2025-05-04 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('coupe', 'Coupé'), ('sedan', 'Berline'), ('suv', 'SUV'), ('hatchback', 'Hayon'), ('convertible', 'Cabriolet'), ('van', 'Van'), ('pickup', 'Pick-up'), ('wagon', 'Break'), ('truck', 'Camion')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la marque')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('image_front', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('image_side', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('habitacl', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('km', models.PositiveIntegerField(help_text='Kilométrage en kilomètres')),
                ('Puissance_fiscale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Origine', models.CharField(choices=[('Dédouanée', 'Dedouanèe'), ('pas encore Dédouanée ', 'pas encore Dédouanée '), ('WW au Maroc', 'WW au Maroc')], max_length=30)),
                ('Première_main', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=30)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendu')], max_length=20)),
                ('Boite_de_vitesses', models.CharField(choices=[('Automatique', 'Automatique'), ('Manuelle', 'Manuelle')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.category')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.marques')),
            ],
        ),
    ]
